### PR TITLE
iteration 2 completed

### PR DESCRIPTION
**Pull request by JWill06**
Co-authored-by: Peter Kim, peterkim.pk1@gmail.com
Co-authored-by: Kim Ewing, pekar.kimberly@gmail.com
Co-authored-by: Marshall Hotaling, marshall.hotaling@gmail.com
Co-authored-by: Jordan Williamson, williamsonjordan05@gmail.com

Iteration 2 is completed. The user can now create ideas and delete any current ideas from the DOM and data model.

### CODE REVIEW

**Comment by JWill06** [comment]
Jordan Williamson: worked on the deleteCards function and event listener for deleting the saved cards.

**Comment by marshallhotaling** [comment]
Helped work on css and html to fix the saved cards function and delete cards function

**Comment by peterkimpk1** [comment]
-saveCards now handles titles too long. Adding event listener to the correct query

**Comment by kiewi16** [comment]
Kim Ewing: helped work on the deleteCards function and the CSS for saved cards.

**Pull request merged**
